import Foundation
import Models

func makeTestKindergartenRaw(
    kindercode: String = "TEST001",
    name: String = "테스트유치원",
    address: String = "서울 강남구 테스트로 1",
    lat: Double = 37.4981,
    lng: Double = 127.0276,
    type: InstitutionType = .public,
    phone: String? = nil,
    homepage: String? = nil,
    operationHours: String? = nil,
    sidoCode: String = "11",
    sigunguCode: String = "11680",
    capacity: Int = 40,
    currentCount: Int = 30,
    classCountAge3: Int = 1,
    classCountAge4: Int = 1,
    classCountAge5: Int = 1,
    capacityAge3: Int = 12,
    capacityAge4: Int = 14,
    capacityAge5: Int = 14,
    currentAge3: Int = 10,
    currentAge4: Int = 10,
    currentAge5: Int = 10,
    classCountMix: Int = 0,
    capacityMix: Int = 0,
    currentMix: Int = 0,
    capacitySpecial: Int = 0,
    currentSpecial: Int = 0,
    establishDate: String = "20160302",
    hasBus: Bool = false,
    busCount: Int = 0,
    mealType: MealType? = nil,
    hasAfterSchool: Bool = false,
    areaPerChild: Double = 4.0,
    hasPlayground: Bool = false,
    buildingYear: Int? = nil,
    floorInfo: String? = nil,
    classroomArea: Double = 100,
    indoorPlaygroundArea: Double = 0,
    outdoorPlaygroundArea: Double = 0,
    teacherCount: Int = 4,
    seniorTeacherCount: Int = 1,
    cctvCount: Int = 4
) -> KindergartenRaw {
    KindergartenRaw(
        kindercode: kindercode,
        name: name,
        address: address,
        lat: lat,
        lng: lng,
        type: type,
        phone: phone,
        homepage: homepage,
        operationHours: operationHours,
        sidoCode: sidoCode,
        sigunguCode: sigunguCode,
        capacity: capacity,
        currentCount: currentCount,
        classCountAge3: classCountAge3,
        classCountAge4: classCountAge4,
        classCountAge5: classCountAge5,
        capacityAge3: capacityAge3,
        capacityAge4: capacityAge4,
        capacityAge5: capacityAge5,
        currentAge3: currentAge3,
        currentAge4: currentAge4,
        currentAge5: currentAge5,
        classCountMix: classCountMix,
        capacityMix: capacityMix,
        currentMix: currentMix,
        capacitySpecial: capacitySpecial,
        currentSpecial: currentSpecial,
        establishDate: establishDate,
        hasBus: hasBus,
        busCount: busCount,
        mealType: mealType,
        hasAfterSchool: hasAfterSchool,
        areaPerChild: areaPerChild,
        hasPlayground: hasPlayground,
        buildingYear: buildingYear,
        floorInfo: floorInfo,
        classroomArea: classroomArea,
        indoorPlaygroundArea: indoorPlaygroundArea,
        outdoorPlaygroundArea: outdoorPlaygroundArea,
        teacherCount: teacherCount,
        seniorTeacherCount: seniorTeacherCount,
        cctvCount: cctvCount
    )
}

func makeTestKindergarten(
    kindercode: String = "TEST001",
    name: String = "테스트유치원",
    address: String = "서울 강남구 테스트로 1",
    lat: Double = 37.4981,
    lng: Double = 127.0276,
    type: InstitutionType = .public,
    capacity: Int = 40,
    currentCount: Int = 30,
    hasBus: Bool = false,
    busCount: Int = 0,
    mealType: MealType? = nil,
    hasAfterSchool: Bool = false,
    areaPerChild: Double = 4.0,
    hasPlayground: Bool = false,
    teacherCount: Int = 4,
    cctvCount: Int = 4,
    distance: Double = 0.5
) -> Kindergarten {
    let raw = makeTestKindergartenRaw(
        kindercode: kindercode,
        name: name,
        address: address,
        lat: lat,
        lng: lng,
        type: type,
        capacity: capacity,
        currentCount: currentCount,
        hasBus: hasBus,
        busCount: busCount,
        mealType: mealType,
        hasAfterSchool: hasAfterSchool,
        areaPerChild: areaPerChild,
        hasPlayground: hasPlayground,
        teacherCount: teacherCount,
        cctvCount: cctvCount
    )
    return Kindergarten(raw: raw, distance: distance)
}
